#pragma once
#include <fstream>
#include <string>
#include <iostream>
#include <cmath>
#include <vector>
#include <array>
#include <Source/Accessory/my_str.h>
#include <Source/Accessory/Thrower.h>
#include <Source/Accessory/miscCommonFunctions.h>